-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 14:26:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cardapio_if
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cardapio_if
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardapio_if` DEFAULT CHARACTER SET utf8 ;
USE `cardapio_if` ;

-- -----------------------------------------------------
-- Table `cardapio_if`.`Nutricionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_if`.`Nutricionista` (
  `idNutricionista` INT NOT NULL AUTO_INCREMENT,
  `emailNutricionista` VARCHAR(100) NOT NULL,
  `senhaNutricionista` TEXT NOT NULL,
  `ultimoLoginNutricionista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idNutricionista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_if`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_if`.`cardapio` (
  `idCardapio` INT NOT NULL AUTO_INCREMENT,
  `idNutricionista` INT NOT NULL,
  `baseCardapio` VARCHAR(45) NULL,
  `principalCardapio` VARCHAR(150) NULL,
  `guarnicaoCardapio` VARCHAR(150) NULL,
  `salada1Cardapio` VARCHAR(100) NULL,
  `salada2Cardapio` VARCHAR(100) NULL,
  `sobremesaCardapio` VARCHAR(100) NULL,
  `sucoCardapio` VARCHAR(50) NULL,
  `dataCardapio` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCardapio`),
  INDEX `idNutricionistax_idx` (`idNutricionista` ASC),
  CONSTRAINT `idNutricionistax`
    FOREIGN KEY (`idNutricionista`)
    REFERENCES `cardapio_if`.`Nutricionista` (`idNutricionista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
